version: '3.8'
# Wordpress Stack for Demos
# Requires
# Net mariadb-public
# Net traefik-public
# Config php_upload_64M
# Secrets   - MARIADB_PASSWORD_SECRET 
# NAME required
# DOMAIN required
# WP_VERSION  optional
# labels on nodes wordpress.demos == 1

configs:
  php_upload_64M:
    external: true

secrets:
  mariadb-password:
    external: true
    name: ${MARIADB_PASSWORD_SECRET}

networks:
  db:
    external: true
    name: ${MARIADB_NET-mariadb-public}
  ingress:
    external: true
    name: ${TRAEFIK_NET-traefik-public}
    
volumes:
  wordpress:
  filebrowser_config:

services:
  wordpress:
    image: wordpress:${WP_VERSION-5.8-php8.0-apache}
    deploy:
      resources:
        limits:
          cpus: ${WP_CPU_LIMIT-'1.66'}
          memory: ${WP_MEMORY_LIMIT-1500M}
        reservations:
          cpus: ${WP_CPU_RESERVATION-'0.25'}
          memory: ${WP_MEMORY_RESERVATION-500M}
      replicas: 1
      placement:
        constraints:
          - node.labels.wordpress.demos == 1
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=${TRAEFIK_NET-traefik-public}
        - traefik.constraint-label=${TRAEFIK_NET-traefik-public}
        - traefik.http.routers.${NAME}-wordpress-http.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-wordpress-http.entrypoints=http
        - traefik.http.routers.${NAME}-wordpress-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-wordpress-https.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)
        - traefik.http.routers.${NAME}-wordpress-https.entrypoints=https
        - traefik.http.routers.${NAME}-wordpress-https.tls=true
        - traefik.http.routers.${NAME}-wordpress-https.tls.certresolver=le
        - traefik.http.services.${NAME}-wordpress.loadbalancer.server.port=${WP_PORT-80}
    configs:
      - source: php_upload_64M
        target: /usr/local/etc/php/conf.d/custom.ini
        mode: 0440
    volumes:
      - wordpress:/var/www/html
    secrets:
      - mariadb-password
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${NAME}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mariadb-password
      WORDPRESS_DB_NAME: ${NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX-wp}_
    networks:
      - ingress
      - db
      
  filebrowser:
    image: hurlenko/filebrowser
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.wordpress.demos == 1
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=${TRAEFIK_NET-traefik-public}
        - traefik.constraint-label=${TRAEFIK_NET-traefik-public}
        - traefik.http.routers.${NAME}-filebrowser-http.rule=Host(`files.cloud.saia.ar`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-http.entrypoints=http
        - traefik.http.routers.${NAME}-filebrowser-http.middlewares=https-redirect
        - traefik.http.routers.${NAME}-filebrowser-https.rule=Host(`files.cloud.saia.ar`) && PathPrefix(`/${NAME}`)
        - traefik.http.routers.${NAME}-filebrowser-https.entrypoints=https
        - traefik.http.routers.${NAME}-filebrowser-https.tls=true
        - traefik.http.routers.${NAME}-filebrowser-https.tls.certresolver=le
        - traefik.http.services.${NAME}-filebrowser.loadbalancer.server.port=${FB_PORT-8080}
    environment:
      FB_BASEURL: "/${NAME}/"
    volumes:
      - wordpress:/data/${NAME}
      - filebrowser_config:/config
    networks:
      - ingress   
  

